In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from preprocess import preprocess_text
from features.vectorizer import Vectorizer
from utils.constants import CATEGORIES, TITLE, ABSTRACT, TEXT_FEATURE
from models.supervised_model import SupervisedModel
import warnings
from tqdm import tqdm

import pickle
warnings.filterwarnings("ignore")

In [10]:
with open("features/count_vectorizer.pkl",'rb') as f:
    cv = pickle.load(f)
cv_y = cv['categories']
cv.drop(columns=['categories'], inplace=True)

In [11]:
with open("features/tfidf_vectorizer.pkl",'rb') as f:
    tfidf = pickle.load(f)
tfidf_y = tfidf['categories']
tfidf.drop(columns=['categories'], inplace=True)

In [12]:
from imblearn.over_sampling import BorderlineSMOTE

In [13]:
sm = BorderlineSMOTE(random_state=42)
X_res, y_res = sm.fit_resample(cv, cv_y)

In [16]:
y_res.value_counts()

0    8814
1    8814
2    8814
3    8814
4    8814
5    8814
6    8814
Name: categories, dtype: int64

In [17]:
sm2 = BorderlineSMOTE(random_state=42)
X_tfidf, y_tfidf = sm2.fit_resample(tfidf, tfidf_y)

In [18]:
X_tfidf

,line,algorithm,relationship,random,paper,introduce,markov,model,linear,space,...,recommender,score,baseline,android,caching,lte,apps,iot,sdn,blockchain
0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
1,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
2,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.062977,0.0,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
4,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61693,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.054534,0.0,0.0,0.0,0.000000,0.0
61694,0.0,0.0,0.000000,0.0,0.0,0.104823,0.0,0.000000,0.0,0.015493,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.017517,0.0
61695,0.0,0.0,0.030863,0.0,0.0,0.034888,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.022140,0.0
61696,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.052514,0.0,0.044408,...,0.0,0.0,0.036514,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0
61697,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.013463,0.0,0.0,0.0,0.000000,0.0

In [19]:
X_res['categories'] = y_res
X_tfidf['categories'] = y_tfidf

In [20]:
X_res

,line,algorithm,relationship,random,paper,introduce,markov,model,linear,space,...,score,baseline,android,caching,lte,apps,iot,sdn,blockchain,categories
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61693,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,6
61694,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
61695,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
61696,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
61697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6

In [21]:
X_res.to_pickle("features/oversampled_count_vectorizer.pkl")
X_tfidf.to_pickle("features/oversampled_tfidf_vectorizer.pkl")